/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_my_gesture_GestureJNI */

#ifndef _Included_com_my_gesture_GestureJNI
#define _Included_com_my_gesture_GestureJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_my_gesture_GestureJNI
 * Method:    hello
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_my_gesture_GestureJNI_hello
  (JNIEnv *, jclass);

/*
 * Class:     com_my_gesture_GestureJNI
 * Method:    editDistance
 * Signature: (II[B[B)I
 */
JNIEXPORT jint JNICALL Java_com_my_gesture_GestureJNI_editDistance
  (JNIEnv *, jclass, jint, jint, jbyteArray, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
